--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/superbobby2000/CommandDisabler
build-by-default: true
branches:
- master
- "PM-4"
- "PM5"
projects:
  CommandDisabler:
    path: ""
    icon: icon.png
...
